# Agentia Architecturalis — codegen.py
# v1.0.0
"""Generate clean Python/PyQt6 code from a design tree."""

import ast
from datetime import datetime

from .constants import TOKEN_NAMES


# Maps element_type to PyQt6 import
_IMPORT_MAP = {
    'QFrame': 'QFrame', 'QGroupBox': 'QGroupBox', 'QSplitter': 'QSplitter',
    'QTabWidget': 'QTabWidget', 'QLabel': 'QLabel', 'QLabel_gold': 'QLabel',
    'QLabel_dim': 'QLabel', 'QLabel_micro': 'QLabel',
    'QLineEdit': 'QLineEdit', 'QComboBox': 'QComboBox',
    'QSlider': 'QSlider', 'QSpinBox': 'QSpinBox',
    'QPushButton': 'QPushButton', 'ArcaneButton_gold': 'QPushButton',
    'ArcaneButton_teal': 'QPushButton', 'ArcaneButton_crimson': 'QPushButton',
    'ToggleButton': 'QPushButton', 'QProgressBar': 'QProgressBar',
    'QTableView': 'QTableWidget', 'QTextEdit': 'QTextEdit',
    'Separator': 'QFrame', 'RuleLine': 'QFrame',
    'Spacer': 'QWidget', 'TopBar': 'QFrame', 'StatusBar': 'QFrame',
    'ControlPanel': 'QFrame', 'SectionHeader': 'QLabel',
    'SwatchStrip': 'QWidget',
}

_LAYOUT_IMPORTS = {'QVBoxLayout', 'QHBoxLayout', 'QGridLayout'}


def _collect_types(nodes: list[dict]) -> set[str]:
    """Recursively collect all element types in the tree."""
    types = set()
    for node in nodes:
        types.add(node.get('element_type', 'QFrame'))
        types.update(_collect_types(node.get('children', [])))
    return types


def _generate_imports(element_types: set[str]) -> str:
    """Produce minimal import block for used element types."""
    widgets = set()
    for et in element_types:
        mapped = _IMPORT_MAP.get(et, 'QWidget')
        widgets.add(mapped)
    widgets.add('QWidget')  # always needed

    # Check if layouts needed
    needs_layouts = any(
        _IMPORT_MAP.get(et) in ('QFrame', 'QGroupBox')
        for et in element_types
    )
    layouts = set()
    if needs_layouts:
        layouts = {'QVBoxLayout', 'QHBoxLayout'}

    # Core Qt imports
    lines = []
    all_widgets = sorted(widgets | layouts)
    lines.append(f"from PyQt6.QtWidgets import ({', '.join(all_widgets)})")

    # Check for Qt.Orientation (sliders, splitters)
    if any(et in ('QSlider', 'QSplitter') for et in element_types):
        lines.append("from PyQt6.QtCore import Qt")

    return '\n'.join(lines)


def _generate_header(class_name: str) -> str:
    """ModusArcanus file header."""
    now = datetime.now().strftime('%Y-%m-%d')
    return f'''# Generated by Agentia Architecturalis — Bureau II
# v1.0.0 — {now}
"""Auto-generated component: {class_name}."""
'''


def generate_code(design: dict, tokens: dict,
                  class_name: str = "GeneratedPanel") -> str:
    """Traverse design tree, emit complete Python module.

    Token values referenced by constant name (C_GOLD, etc.),
    not hardcoded hex values.
    """
    root_elements = design.get('root_elements', [])
    element_types = _collect_types(root_elements)

    # Build constant definitions from tokens
    const_lines = []
    for name in TOKEN_NAMES:
        const_name = f"C_{name.upper()}"
        hex_val = tokens.get(name, '#000000')
        const_lines.append(f'{const_name} = "{hex_val}"')

    # Build the element code via element factory
    from .elements.factory import deserialize_element
    body_lines = []
    for node in root_elements:
        element = deserialize_element(node)
        code_lines = element.generate_code(tokens, indent=2)
        body_lines.extend(code_lines)

    # Assemble
    header = _generate_header(class_name)
    imports = _generate_imports(element_types)
    constants = '\n'.join(const_lines)

    init_body = '\n'.join(body_lines) if body_lines else '        pass'

    code = f"""{header}
{imports}

# Color tokens — from active theme
{constants}


class {class_name}(QFrame):
    \"\"\"Generated component panel.\"\"\"

    def __init__(self, parent=None):
        super().__init__(parent)
        self._build()

    def _build(self):
{init_body}
"""

    # Sanity check
    try:
        ast.parse(code)
    except SyntaxError as e:
        raise SyntaxError(
            f"Generated code has syntax error at line {e.lineno}: {e.msg}"
        ) from e

    return code
